markets/urls.py
from django.conf.urls import url

from . import views

app_name = 'markets'

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<market_id>[0-9]+)/securities/$', views.securities, name='securities')
]

stocks/urls.py
from django.conf.urls import url

from . import views

app_name = 'stocks'

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
  url(r'^(?P<stock_id>[0-9]+)/vote/$', views.vote, name='vote')
]

trading/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^markets/', include('markets.urls')),
    url(r'^admin/', admin.site.urls),
]

markets/models.py
from django.db import models

class Sector(models.Model):
  name = models.CharField(max_length=50)
  def __str__(self):
    return self.name

class Market(models.Model):
  sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
  name = models.CharField(max_length=50)
  def __str__(self):
    return self.name

class SecurityType(models.Model):
  name = models.CharField(max_length=50)
  def __str__(self):
    return self.name

class Security(models.Model):
  market = models.ForeignKey(Market, on_delete=models.CASCADE)
  security_type = models.ForeignKey(SecurityType, on_delete=models.CASCADE)
  name = models.CharField(max_length=100)
  ticker = models.CharField(max_length=20)
  def __str__(self):
    return self.ticker

stocks/models.py
from django.db import models

class Stock(models.Model):
  ticker = models.CharField(max_length=20)
  daily_volume = models.IntegerField(default=0)
  def __str__(self):
    return self.ticker

class Trade(models.Model):
  stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
  type = models.CharField(max_length=20)
  purchase_price = models.DecimalField(max_digits=12, decimal_places=2)
  sale_price = models.DecimalField(max_digits=12, decimal_places=2)
  def __str__(self):
    return self.type + ": " + str(self.purchase_price)
  def is_short(self):
    return self.type == "Short"
  def is_long(self):
    return self.type == "Long"

markets/views.py
mck\irom django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.core import serializers
from django.views import generic
from bokeh.client import push_session
from bokeh.embed import autoload_server
from bokeh.plotting import figure, curdoc
from bokeh.mpl import to_bokeh
from .lib.jambala import Jambala

from .models import Sector, Market, SecurityType, Security

class IndexView(generic.ListView):
  template_name = 'markets/index.html'
  context_object_name = 'markets_list'

  def get_queryset(self):
    queryset = {}
    queryset['markets'] = Market.objects.order_by('name').all
    queryset['script'] = self.get_chart()
    queryset['data'] = self.get_data(['GOOG'], '01/01/2016', '01/02/2016')
    return queryset

  def get_chart(self):
    session = push_session(curdoc())
    doc = to_bokeh(self.get_data(['GOOG'], '01/01/2016', '01/30/2016'))
    curdoc().add(doc)
    return autoload_server(doc, session_id=session.id)

  def get_data(self, securities, from_date, to_date):
    j = Jambala(securities, from_date, to_date)
    return j.fetch()

def securities(request, market_id):
  market = Market.objects.get(pk=market_id)
  securities = serializers.serialize('json', market.security_set.order_by('name').all(), fields=('ticker', 'name'))
    return item
  return JsonResponse(securities, safe=False)

stocks/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Stock, Trade

class IndexView(generic.ListView):
  template_name = 'stocks/index.html'
  context_object_name = 'stocks_list'

  def get_queryset(self):
    return Stock.objects.order_by('ticker').all()

class DetailView(generic.DetailView):
  model = Stock
  template_name = 'stocks/detail.html'

class ResultsView(generic.DetailView):
  model = Stock
  template_name = 'stocks/results.html'

def vote(request, stock_id):
  stock = get_object_or_404(Stock, pk=stock_id)
  try:
    selected_trade = stock.trade_set.get(pk=request.POST['trade'])
  except (KeyError, Trade.DoesNotExist):
    return render(request, 'stocks/detail.html', {'stock': stock, 'error_message': "You didn't select a trade."})
  else:
    selected_trade.purchase_price += 1
    selected_trade.save()
    return HttpResponseRedirect(reverse('stocks:results', args=(stock.id,)))

markets/templates/markets/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'markets/css/bootstrap-datepicker3.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'markets/css/style.css' %}" />
<link
    href="http://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.css"
    rel="stylesheet" type="text/css">
<script src="http://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.js"></script>
{% endblock %}

{% block content %}

{% if markets_list.markets %}
    <div class="row">
      <form method="post">
        <div class="form-group col-md-1">
          <label for="markets">Market: </label>
          <select name="markets" id="markets" class="form-control">
          <option value=""></option>
          {% for market in markets_list.markets %}
            <option value="{{ market.id }}">{{ market }}</option>
          {% endfor %}
          </select>
        </div>
        <div class="hidden" id="securities_div">
          <div class="form-group col-md-4">
            <label for="securities">Security: </label>
            <select name="securities" id="securities" class="form-control" multiple="multiple"></select>
          </div>
          <div class="col-md-2">
            <div class="form-group">
                <label for="from_date">From: </label>
                <input name="from_date" id="from_date" class="form-control datepicker">
            </div>
            <div class="form-group">
                <label for="to_date">To: </label>
                <input name="to_date" id="to_date" class="form-control datepicker">
            </div>
          </div>
          <!--<div class="col-md-3">
            <div class="form-group">
                <label for="from_date">From: </label>
                <input name="from_date" id="from_date" class="form-control datepicker">]
            </div>
            <div class="form-group">
                <label for="to_date">To: </label>
                <input name="to_date" id="to_date" class="form-control datepicker">
            </div>
          </div> -->
        </div>
      </form>
    </div>
    <div class="row" id="chart">
      {{ markets_list.script | safe }}
    </div>
{% else %}
  <p>No Markets.</p>
{% endif %}
{% endblock %}

{% block scripts %}
<script src="{% static 'markets/js/bootstrap-datepicker.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'markets/js/markets.js' %}" crossorigin="anonymous"></script>
{% endblock %}

stocks/templates/stocks/detail.html
<h1>{{ stock.ticker }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p><b>Daily Volume:</b> {{ stock.daily_volume }}</p>
<form action="{% url 'stocks:vote' stock.id %}" method="post">
{% csrf_token %}
{% for trade in stock.trade_set.all %}
  <input type="radio" name="trade" id="trade{{ forloop.counter }}" value="{{ trade.id }}" />
  <label for="trade{{ forloop.counter }}">{{ trade }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

stocks/templates/stocks/index.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'stocks/style.css' %}" />

{% if stocks_list %}
  <ul>
  {% for stock in stocks_list %}
    <li><a href="{% url 'stocks:detail' stock.id %}">{{ stock.ticker }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No Stocks.</p>
{% endif %}
{% endblock %}

stocks/templates/stocks/results.html
<h1>{{ stock.ticker }}</h1>
<ul>
{% for trade in stock.trade_set.all %}
  <li>{{ trade }}</li>
{% endfor %}
</ul>

<a href="{% url 'stocks:detail' stock.id %}">Trade Again?</a>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Trading Desk</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block styles %}{% endblock %}
  </head>
  <body>
    <div class="container-fluid">
      <h1>Trading Desk</h1>
      {% block content %}{% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>